# Dockerfile para PHP + Composer + MongoDB PECL
FROM php:8.3-cli

# Instalar dependencias necesarias para PECL
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libsasl2-dev \
    curl \
    unzip \
    git \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb \
    && rm -rf /var/lib/apt/lists/*

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
