GET http://localhost:8000/api/products HTTP/1.1
Authorization: Bearer 2|IVGvZUkHlRIBohViDDsuX7BYLvehzPFMDu4eawdh8145143c
Accept: application/json

###
POST http://localhost:8000/api/products HTTP/1.1
Authorization: Bearer 2|IVGvZUkHlRIBohViDDsuX7BYLvehzPFMDu4eawdh8145143c
Content-Type: application/json
Accept: application/json

{
    "nombre" : "Prueba",
    "descripcion" : "Esto es una prueba",
    "precio" : 15,
    "foto" : null
}

###
GET http://localhost:8000/api/products/6 HTTP/1.1
Authorization: Bearer 2|IVGvZUkHlRIBohViDDsuX7BYLvehzPFMDu4eawdh8145143c
Accept: application/json

###
PUT http://localhost:8000/api/products/8 HTTP/1.1
Authorization: Bearer 2|IVGvZUkHlRIBohViDDsuX7BYLvehzPFMDu4eawdh8145143c
Content-Type: application/json
Accept: application/json

{
    "nombre" : "Prueba2",
    "descripcion" : "Esto es una prueba",
    "precio" : 155555,
    "foto" : null
}

###
DELETE http://localhost:8000/api/products/6 HTTP/1.1
Authorization: Bearer 2|IVGvZUkHlRIBohViDDsuX7BYLvehzPFMDu4eawdh8145143c
Accept: application/json

###

POST http://localhost:8000/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "arganis@mail.com",
    "password": "1234"
}

###
POST http://localhost:8000/api/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "victor",
    "email": "victor@mail.com",
    "password": "1234"
}
