services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: empledepart
      MYSQL_USER: usuario_js
      MYSQL_PASSWORD: seguro
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Importación del archivo SQL
      - ./databases/:/docker-entrypoint-initdb.d/
    # Opcional: Si quieres que importe todo lo que haya en esa carpeta:
    # - ./databases:/docker-entrypoint-initdb.d

  workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql_workbench
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: